

services:
  # 1. Contenedor de la Aplicación (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app-postgres
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  # 2. Contenedor de la Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laraveluser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "5432:5432" # Puerto estándar de PostgreSQL
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata: